version: "3.4"

# Global configurations that 
x-global-envs: &env_variables
  environment:
    # Default passwod for postgres
    POSTGRES_PASSWORD: Passw0rd

    # https://github.com/indian2569/pes-app-angular/blob/master/backend/src/main/resources/application-postgres.yaml
    DB_JDBC_URL: "jdbc:postgresql://db/pes_prod?currentSchema=pes"
    # XXX fix the application and use DB_USER_APP for application and DB_USER_OWN for flyway
    DB_USERNAME: postgres
    DB_PASSWORD: Passw0rd

    DB_USER_APP: ta_pes
    DB_USER_APP_PASSWORD: ta_pes
    DB_USER_OWN: ta_pes_own
    DB_USER_OWN_PASSWORD: ta_pes_own

    # For postgresql admin scripts
    AWT_TA_AWT_OWN_PASSWORD: ta_pes_own
    AWT_TA_AWT_PASSWORD: ta_pes
    AWT_TA_DB_NAME: pes

x-build-args: &build_args
  args:
    VERSION: 1.0.0-SNAPSHOT

# 
#   Application
#
services:
    db:
        # Global env variables
        << : *env_variables
        image: postgres:13.4-alpine
        volumes:
          - ./pes-spring/src/main/resources/db/admin_script:/docker-entrypoint-initdb.d
        # Expose ports
        ports:
         - "5434:5432"

    app:
        build:
            context: ./pes-spring
        container_name: app
        ports:
          - 8080:8080
        links:
          - db:db
        depends_on:
          - db

    angular:
        build:
          context: angular
          target: builder
        container_name: angular
        ports: 
          - 4200:4200
        depends_on:
          - app
        volumes:
          - ./angular:/project
          - /project/node_modules

