version: '3'

# Global configurations that 
x-global-envs: &env_variables
  environment:
    # Default passwod for postgres
    POSTGRES_PASSWORD: Passw0rd

    # https://github.com/indian2569/pes-app-angular/blob/master/backend/src/main/resources/application-postgres.yaml
    DB_JDBC_URL: "jdbc:postgresql://db/pes?currentSchema=pes"
    # XXX fix the application and use DB_USER_APP for application and DB_USER_OWN for flyway
    DB_USERNAME: postgres
    DB_PASSWORD: Passw0rd

    DB_USER_APP: ta_pes
    DB_USER_APP_PASSWORD: ta_pes
    DB_USER_OWN: ta_pes_own
    DB_USER_OWN_PASSWORD: ta_pes_own

    # For postgresql admin scripts
    AWT_TA_AWT_OWN_PASSWORD: ta_pes_own
    AWT_TA_AWT_PASSWORD: ta_pes
    AWT_TA_DB_NAME: pes

x-build-args: &build_args
  args:
    VERSION: 1.0.0-SNAPSHOT

# 
#   Application
#
services:
    postgres:
        # Global env variables
        << : *env_variables
        image: postgres:14.1-alpine

        # Push in admin script
        volumes:
          - ./pes-spring/src/main/resources/db/admin_script:/docker-entrypoint-initdb.d
        
        # Expose ports
        ports:
          - "5434:5432"
        networks:
         - backendNetwork
 
    spring-boot-ems:
        image: maven:3.6.3-jdk-11
        container_name: spring-boot-ems
        ports:
          - 8080:8080
        depends_on:
          - postgres
        volumes:
          - ./pes-spring/target/pes-1.0.0-SNAPSHOT.jar:/pes-app.jar
        command: ["java", "-jar", "pes-app.jar"]
        networks:
          - backendNetwork
          - frontendNetwork

    angular:
        image: nginx:alpine
        container_name: angular
        ports: 
          - 4200:80
        depends_on:
          - spring-boot-ems
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./angular/dist/angular/:/usr/share/nginx/html
        networks:
          - frontendNetwork


volumes:
  dockerPessData:
  
networks:
  backendNetwork:
  frontendNetwork: