spring:
  h2:
    console:
      enabled: false
      settings.web-allow-others: false
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5434/pes_prod?currentSchema=pes}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Passw0rd}
    hikari:
      idleTimeout: 30000
      minimumIdle: 2
      maximumPoolSize: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: ${DB_SHOW_SQL:false}
#    properties.hibernate.default_schema: pes
  flyway:
    enabled: ${DB_AUTO_UPDATE:true}
    locations: classpath:db/specific/postgres
    