spring:
  h2:
    console:
      enabled: false
      settings.web-allow-others: false
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: ${DB_JDBC_URL:jdbc:postgresql://${DB_JDBC_HOST:db}:${DB_JDBC_PORT:5432}/${DB_JDBC_NAME:pes_prod}?currentSchema=${DB_JDBC_SCHEMA:pes}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Passw0rd}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: ${DB_SHOW_SQL:false}
#    properties.hibernate.default_schema: pes
  flyway:
    enabled: ${DB_AUTO_UPDATE:true}
    locations: classpath:db/specific/postgres
    